import os
import json
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from dotenv import load_dotenv

load_dotenv()


# Report Formatter Helpers

def _health_bar(score: int) -> str:
    filled = round(score / 10)
    return "█" * filled + "░" * (10 - filled) + f"  {score}/100"


def _badge(label: str, value: str) -> str:
    return f"`{label}: {value}`"


@tool
def format_report(analysis_json: str, github_url: str) -> str:
    """
    Format analysis JSON into a clean markdown report.
    Input: JSON string from analyser-agent, and the original GitHub URL.
    Returns: formatted markdown string ready to display.
    """
    try:
        clean = analysis_json.strip()
        if clean.startswith("```"):
            clean = clean.split("```")[1]
            if clean.startswith("json"):
                clean = clean[4:]
        data = json.loads(clean.strip())
    except Exception:
        return f"# GitGist Report\n\n**Source:** {github_url}\n\n{analysis_json}"

    # Build health bar
    health = data.get("health_score", 0)
    bar = _health_bar(health)

    # Tech stack badges
    stack = data.get("tech_stack", [])
    stack_str = "  ".join(f"`{t}`" for t in stack) if stack else "_unknown_"

    # Open problems
    problems = data.get("open_problems", [])
    problems_md = "\n".join(f"- {p}" for p in problems) if problems else "- None reported"

    # Key features
    features = data.get("key_features", [])
    features_md = "\n".join(f"- {f}" for f in features) if features else "- Not detected"

    # Prerequisites
    prereqs = data.get("prerequisites", [])
    prereqs_md = ", ".join(prereqs) if prereqs else "None"

    # Health reasons
    health_reasons = data.get("health_reasons", [])
    health_md = "\n".join(f"- {r}" for r in health_reasons)

    # Advanced Features Extract

    # Dependencies
    deps = data.get("dependencies", {})
    deps_score = deps.get("security_score", 100)
    deps_bar = _health_bar(deps_score)
    deps_issues = deps.get("issues", [])
    deps_issues_md = "\n".join(f"- {i}" for i in deps_issues) if deps_issues else "- No dependency issues found."

    # Tree
    tree_md = data.get("directory_tree", "Not found").strip()

    # Code Quality
    quality = data.get("code_quality_review", {})
    quality_rating = quality.get("rating", "?")
    readability = quality.get("readability", "No details.")
    bottlenecks = quality.get("bottlenecks", "None detected.")
    suggestions = quality.get("suggestions", [])
    suggestions_md = "\n".join(f"- {s}" for s in suggestions) if suggestions else "- No suggestions."

    # Community Health
    comm = data.get("community_health", {})
    open_prs = comm.get("open_prs", "?")
    activity_summary = comm.get("activity_summary", "No activity summary available.")

    report = f"""# 🔍 GitGist Report

**{data.get('project_name', 'Unknown Project')}**
{data.get('one_line_summary', '')}

🔗 [{github_url}]({github_url})

## 📊 At a Glance

| Property | Value |
|---|---|
| **Maturity** | {data.get('project_maturity', '?')} |
| **Activity** | {data.get('activity_level', '?')} |
| **Complexity** | {data.get('complexity', '?')} |
| **Setup Difficulty** | {data.get('setup_difficulty', '?')} |
| **Est. Setup Time** | {data.get('estimated_setup_minutes', '?')} min |
| **For** | {data.get('target_audience', '?')} |

## 🏥 Health Score

{bar}

{health_md}

## 🛠️ Tech Stack

{stack_str}

## ✨ Key Features

{features_md}

## 🚀 Getting Started

{data.get('getting_started', '_No setup info found._')}

**Prerequisites:** {prereqs_md}

## 📦 Dependencies & Security

**Dependency Security Score:**
{deps_bar}

**Identified Package Issues:**
{deps_issues_md}

## 🌳 Repository Directory Tree

```
{tree_md}
```

## 🔬 Automated Code Quality Review

**Overall Snippet Grade: `{quality_rating}`**

- **Readability:** {readability}
- **Bottlenecks & Debt:** {bottlenecks}

**Refactoring Suggestions:**
{suggestions_md}

## 🤝 Community & Contribution Health

- **Open Pull Requests:** `{open_prs}`
- **Activity Assessment:** {activity_summary}

## 🐛 Open Problems

{problems_md}

---
_Generated by GitGist · Powered by Zynd × Apify × Superplane_
"""
    return report.strip()


# Agent Setup

def get_reporter_executor() -> AgentExecutor:
    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0,
        base_url=os.environ.get("OPENAI_API_BASE") or os.environ.get("OPENAI_BASE_URL") or None
    )
    tools = [format_report]

    prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """You are a report formatter for the GitGist system.
You receive a JSON analysis and a GitHub URL.
Your input will be in this format:
  JSON: <analysis json>
  URL: <github url>

Extract the JSON and URL, call format_report with both, and return the result exactly as-is.
Do not add any extra text."""
        ),
        ("human", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ])

    agent = create_tool_calling_agent(llm, tools, prompt)
    return AgentExecutor.from_agent_and_tools(
        agent=agent, tools=tools, verbose=True
    )


# Unified entry point

def run_reporter(analysis_json: str, github_url: str) -> str:
    """Run the in-memory reporter tool directly to bypass slow LLM loops and prevent timeouts."""
    print("[Direct Reporter] Formatting report...")
    try:
        return format_report.invoke({"analysis_json": analysis_json, "github_url": github_url})
    except Exception as e:
        print(f"[Reporter Fallback] Direct formatting failed, falling back to agent loop: {e}")
        executor = get_reporter_executor()
        reporter_input = f"JSON: {analysis_json}\nURL: {github_url}"
        res = executor.invoke({"input": reporter_input})
        return res.get("output", "")
